/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiTodosServerRouteImport } from './routes/api/todos'
import { ServerRoute as ApiTodosUpdateServerRouteImport } from './routes/api/todos.update'
import { ServerRoute as ApiTodosCreateServerRouteImport } from './routes/api/todos.create'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosServerRoute = ApiTodosServerRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTodosUpdateServerRoute = ApiTodosUpdateServerRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiTodosServerRoute,
} as any)
const ApiTodosCreateServerRoute = ApiTodosCreateServerRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiTodosServerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/todos': typeof ApiTodosServerRouteWithChildren
  '/api/todos/create': typeof ApiTodosCreateServerRoute
  '/api/todos/update': typeof ApiTodosUpdateServerRoute
}
export interface FileServerRoutesByTo {
  '/api/todos': typeof ApiTodosServerRouteWithChildren
  '/api/todos/create': typeof ApiTodosCreateServerRoute
  '/api/todos/update': typeof ApiTodosUpdateServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/todos': typeof ApiTodosServerRouteWithChildren
  '/api/todos/create': typeof ApiTodosCreateServerRoute
  '/api/todos/update': typeof ApiTodosUpdateServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/todos' | '/api/todos/create' | '/api/todos/update'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/todos' | '/api/todos/create' | '/api/todos/update'
  id: '__root__' | '/api/todos' | '/api/todos/create' | '/api/todos/update'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiTodosServerRoute: typeof ApiTodosServerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/todos/update': {
      id: '/api/todos/update'
      path: '/update'
      fullPath: '/api/todos/update'
      preLoaderRoute: typeof ApiTodosUpdateServerRouteImport
      parentRoute: typeof ApiTodosServerRoute
    }
    '/api/todos/create': {
      id: '/api/todos/create'
      path: '/create'
      fullPath: '/api/todos/create'
      preLoaderRoute: typeof ApiTodosCreateServerRouteImport
      parentRoute: typeof ApiTodosServerRoute
    }
  }
}

interface ApiTodosServerRouteChildren {
  ApiTodosCreateServerRoute: typeof ApiTodosCreateServerRoute
  ApiTodosUpdateServerRoute: typeof ApiTodosUpdateServerRoute
}

const ApiTodosServerRouteChildren: ApiTodosServerRouteChildren = {
  ApiTodosCreateServerRoute: ApiTodosCreateServerRoute,
  ApiTodosUpdateServerRoute: ApiTodosUpdateServerRoute,
}

const ApiTodosServerRouteWithChildren = ApiTodosServerRoute._addFileChildren(
  ApiTodosServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiTodosServerRoute: ApiTodosServerRouteWithChildren,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
